---
- name: Virtualenv
  apt: name={{ item }}
  with_items:
    - python-virtualenv
    - python3-setuptools
- name: Create virtualenv
  # We do this here since Ansible only has virtualenv_python in 2.x
  become_user: socialrelay
  command: creates=/home/socialrelay/venv virtualenv -p python3.4 /home/socialrelay/venv
- name: Update pip and setuptools
  pip: name={{ item }} state=latest virtualenv=/home/socialrelay/venv
  become_user: socialrelay
  with_items:
    - pip
    - setuptools
